apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: school-app-v2
  name: school-app-v2
spec:
  replicas: 0
  selector:
    matchLabels:
      run: school-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        run: school-app
    spec:
      containers:
      - image: mangeshabnave/cgi-app-v2
        name: school-app
