apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superadmin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
