apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: superadmin-binding
subjects:
- kind: User
  name: john # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: superadmin
  apiGroup: rbac.authorization.k8s.io
