apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: appname
      valueFrom:
        configMapKeyRef:
          name: mycm-5
          key: channel.name
    - name: dataproperties
      valueFrom:
        configMapKeyRef:
          name: mycm-5 
          key: dabatase_IP
