apiVersion: v1
kind: Pod
metadata:
  name: podnodeaffinity-1
spec:
  containers:
    - image: nginx
      name: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "demoserver"
              operator: In
              values:
              - "true"
