apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret-2
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    envFrom:
    - secretRef:
          name: demo-secret
